### ISSUE TITLE
Fix GeoNode and Geoserver communication

### ISSUE THREAD

**Issue by code-geek** [GFDRR/Nepal-Geonode#1]
Maps > Create Maps is throwing an error when trying to add a layer

![image](https://user-images.githubusercontent.com/4883631/34153233-696fd036-e4d9-11e7-93c8-cdb648150dfd.png)

**Comment by afabiani** [comment]
That could be an issue of the settings.

It is possible that the Local GeoServer is pointing to "http://localhost:8080/geoserver", which, of course, is not reachable from outside.

**Comment by code-geek** [comment]
Thanks for your help @afabiani. As you mentioned, I'd most likely messed up when setting up the Geoserver's oauth data folder. I've updated the Nepal GeoNode to 2.8 and fixed this issue.
