### ISSUE TITLE
Raster layers not loading correctly

### ISSUE THREAD

**Issue by code-geek** [GFDRR/Nepal-Geonode#2]
For example, http://geonode.ashishacharya.com/layers/geonode:koshi_baseline_scenario_flooding_rp050#map=107.1212247426634/9688532.79/3069598.57/0

...loads up fine on QGIS, but not on the GeoNode. Almost all the raster layers on the GeoNode are rendering with a solid black rectangle. Is this a projection issue?

**Comment by afabiani** [comment]
Hi, you have to generate and upload a specific SLD to GeoServer in order to render raster layers correctly.

If they are images (RGB as an instance) the default raster style should allow you to see them anyway.

**Comment by code-geek** [comment]
Thanks @afabiani. Closing this because upgrading to 2.8 has fixed the issue. :)
