### ISSUE TITLE
Can't download rasters

### ISSUE THREAD

**Issue by code-geek** [GFDRR/Nepal-Geonode#4]
For example, trying to download [this](http://geonepal.info/layers/geonode:npl2025adjustedbirths) raster throws the following error:

`illegal bbox, minX: 80.05222511269886 is greater than maxX: 26.348658288889002 []`

I found a similar issue on the main GeoNode repo from a while ago:
https://github.com/GeoNode/geonode/issues/1485

It's not immediately clear what the fix is.

**Comment by giohappy** [comment]
Hi @code-geek links in GeoNode's DB seem corrupted. 
Try running the following query to fix them:

```
UPDATE base_resourcebase SET csw_anytext = regexp_replace(csw_anytext,
'(b|Bb|Box)=(-?\d+.?\d+)(,|\%2C)(-?\d+.?\d+)(,|\%2C)(-?\d+.?\d+)(,|\%2C)(-?\d+.?\d+)', -- pattern text
E'\\1=\\2\\3\\6\\5\\4\\7\\8', -- replacement text
'g')-- flags
```

see https://github.com/GFDRR/geonode/issues/20#issuecomment-318091409

**Comment by code-geek** [comment]
Sorry for the late reply, and thank you very much @giohappy! This worked like a charm.
